### ISSUE TITLE
Suggestions for improving the paper

### ISSUE THREAD

**Issue by krother** [TJKessler/ECNet#3]
In my opinion, the paper would gain a bit more clarity by:

* describing specifically what data/features ECNet predicts from (e.g. after 1st sentence would be a good place)
* briefly explaining why the split into nodes is done (prediction quality, distributed computing)
* adding the last paragraph from the README (Using ECNet, T. Kessler et al. have..)

**Comment by krother** [comment]
also reference T. Sennott et al. could go into the paper (just copy).

**Comment by TJKessler** [comment]
To increase clarity, information on what inputs/outputs are used and why nodes are used has been added to the manuscript. Additionally, information present in the README (suggested references) has been added.

**Comment by krother** [comment]
OK, also found Sennott in the reference section of the PDF (didnt spot it in the sources at first sight).
