### ISSUE TITLE
Documentation: format of CSV files

### ISSUE THREAD

**Issue by krother** [TJKessler/ECNet#4]
How are the CSV files structured. I see that line 4 contains the column labels, and line 5+ contains the data (referring to cn_model_v1.0.csv). Two things are unclear to me:

- What do lines 1-3 do?
- Which one is the target column (the values being predicted)

I think both should be documented briefly (e.g. bottom of README.md).

**Comment by TJKessler** [comment]
Documentation regarding database formatting has been included in the README to address your questions.
